base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.homePage, name='home_page'),
    path('login/', views.loginPage, name='login_page'),
    path('register/', views.registerPage, name='register_page'),
    path('logout/', views.logoutUser, name='logout'),
    path('kyc/', views.kycForm, name='kyc_form'),
    path('kyc/batch_list', views.kycHomePage, name='kyc_home_page'),
    path('kyc/<str:pk>', views.kycStudentDetails, name='kyc_details'),
    path('spf/', views.spfForm, name='spf_form'),
    path('spf/batch_list', views.spfHomePage, name='spf_home_page'),
    path('spf/<str:pk>', views.spfStudentDetails, name='spf_details'),
    path('create_drive/', views.createDrive, name='create_drive'),
    path('create_chat', views.createChatRoom, name='create_chat'),
    path('chat/<str:pk>', views.room, name='chat_room'),
    path('tyl/<str:name>', views.tylHomePage, name='tyl_home_page'),
    path('tyl/create_test/<str:name>', views.createTest, name='tyl_create_test'),
    path('tyl/create_assigment/<str:pk>', views.createSubTest, name='tyl_create_sub_test'),
    path('tyl/test_details/<str:pk>', views.tylTestPage, name='tyl_trainer_test_details'),
    path('tyl/upload_marks/<str:pk>', views.uploadTestMarks, name='upload_marks'),
    path('message/delete/<str:pk>', views.deleteMessage, name='delete_message'),
    path('dashboard/spf_kyc/<str:pk>', views.spfKycDashboard, name='spf_kyc_dashboard'),
    path('spad/<str:batch>', views.spadDetails, name='spad_details'),
    path('user_profile/<str:pk>', views.user_profile, name='user_profile'),
    path('user_profile_update', views.user_profile_update, name='user_update'),
    path('dashboard/assignments/batch/<int:batch_id>/test/<int:test_id>/', views.subTestDashboard, name='sub_test_dashboard'),
    path('delete/<str:pk>/', views.delete_room, name='delete_room'),
    path('delete/<str:pk>', views.delete_message, name='delete_message'),
    # path('edit/<str:pk>', views.edit_room, name='edit_room'),
]   

cmritplacementportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime

from .validators import *

class User(AbstractUser):
    name = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    avatar = models.ImageField(null=True, default='avatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

class Batch(models.Model):
    batch_year = models.IntegerField()

    def __str__(self):
        return str(self.batch_year)
    
class Students(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    branch = models.CharField(max_length=200)
    usn = models.CharField(max_length=20, null=True, validators=[validate_usn])
    aptitudeLevel = models.IntegerField(default=0)
    languageLevel = models.IntegerField(default=0)
    programmingLevel = models.IntegerField(default=0)
    coreLevel = models.IntegerField(default=0)
    softskillsLevel = models.IntegerField(default=0)
    placedCount = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.usn} : {self.student.name}'

class KYC(models.Model):
    CHOICES = (
        ('Approved', 'Approved'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected')
    )
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    resume = models.FileField(blank=True, null=True)
    videoResume = models.FileField(blank=True, null=True)
    collegeIdCard = models.FileField(blank=True, null=True)
    passportSizePhoto = models.FileField(blank=True, null=True)
    panCard = models.FileField(blank=True, null=True)
    aadharCard = models.FileField(blank=True, null=True)
    passport = models.FileField(blank=True, null=True)
    tenthMarksCard = models.FileField(blank=True, null=True)
    twelfthMarksCard = models.FileField(blank=True, null=True)
    ugMarksSheet = models.FileField(blank=True, null=True)
    pgMarksSheet = models.FileField(blank=True, null=True)
    cgpaCalculator = models.FileField(blank=True, null=True)

    validation = models.CharField(max_length=10, choices=CHOICES, default='Pending')
    comments = models.TextField(default="No comments")

    def __str__(self):
        return f'KYC: {self.student.student.name}'
    
class SPF(models.Model):
    APPROVAL_CHOICES = (
        ('Approved', 'Approved'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected')
    )
    DEGREE_CHOICES = (
        ('BE', 'BE'),
        ('MCA', 'MCA'),
        ('MBA', 'MBA')
    )
    DEPARTMENT_CHOICES = (
        ('Basic Science', 'Basic Science'),
        ('Placement', 'Placement'),
        ('CSE', 'CSE'),
        ('ISE', 'ISE'),
        ('ECE', 'ECE'),
        ('EEE', 'EEE'),
        ('MECH', 'MECH'),
        ('AIML', 'AIML'),
        ('CIV', 'CIV'),
        ('MCA', 'MCA'),
        ('MBA', 'MBA')
    )
    TYPE_OF_ENTRY_CHOICES = (
        ('Regular', 'Regular'),
        ('Lateral', 'Lateral')
    )
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    UG_PG_CHOICE = (
        ('UG', 'UG'),
        ('PG', 'PG')
    )
    BOOLEAN_CHOICES = (
        ('Yes', 'Yes'),
        ('No', 'No')
    )
    student = models.ForeignKey(Students, on_delete=models.CASCADE, null=False)
    mobileNumberForCalling = models.CharField(max_length=10, null=False)
    mobileNumberForWhatsapp = models.CharField(max_length=10, null=False)
    degree = models.CharField(max_length=3, null=False, choices=DEGREE_CHOICES, default='BE')
    typeOfEntry = models.CharField(max_length=10, choices=TYPE_OF_ENTRY_CHOICES, default='Regular', null=False)
    gender = models.CharField(max_length=6, null=False, choices=GENDER_CHOICES)
    dateOfBirth = models.DateField()
    personalEmailId = models.EmailField()
    mentorName = models.CharField(max_length=20, null=False)
    mentorDept = models.CharField(max_length=13, null=False, choices=DEPARTMENT_CHOICES)
    mentorMobileNumber = models.CharField(max_length=10, null=False)
    parentsMobileNumber = models.CharField(max_length=10, null=False)
    communicationAddress = models.TextField(null=False)
    permanentAddress = models.TextField(null=False)
    tenthMarks = models.FloatField(null=False)
    tenthYearOfPassing = models.CharField(max_length=4, null=False)
    twelfthMarks = models.FloatField(null=True, blank=True, default=0)
    twelfthYearOfPassing = models.CharField(max_length=4, null=True, blank=True, default=0)
    diplomaMarks = models.FloatField(null=True, blank=True, default=0)
    diplomaYearOfPassing = models.CharField(max_length=4, null=True, blank=True, default=0)
    ugOrPg = models.CharField(max_length=2, choices=UG_PG_CHOICE, default='UG', null=False)
    degreeCgpa = models.FloatField(null=False)
    currentBacklogs = models.IntegerField(default=0)
    backlogHistory = models.CharField(max_length=3, choices=BOOLEAN_CHOICES, default='No', null=False)
    yearBack = models.CharField(max_length=3, choices=BOOLEAN_CHOICES, default='No', null=False)
    numberOfYearGapsInAcademics = models.IntegerField(default=0)
    numberofYearGapsInDegree = models.IntegerField(default=0)
    
    validation = models.CharField(max_length=10, choices=APPROVAL_CHOICES, default='Pending')
    comments = models.TextField(default="No comments")

    def __str__(self):
        return f'SPF: {self.student.student.name}'

class Tests(models.Model):
    # Aptitude, Language
    TYL_CHOICES = (
        ('Aptitude', 'Aptitude'),
        ('Language', 'Language'),
        ('Core', 'Core'),
        ('Programming', 'Programming'),
        ('Soft Skills', 'Soft Skills'),
    )
    testName = models.CharField(max_length=200)
    testType = models.CharField(max_length=20, choices=TYL_CHOICES)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    maxMarks = models.FloatField(default=100)
    passingMarks = models.FloatField(default=50)

    def __str__(self):
        return self.testName

class StudentAptitudeTestScores(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    marksObtained = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.test} - {self.student}'

class StudentSoftSkillsTestScores(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    marksObtained = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.test} - {self.student}'

class StudentLanguageTestScores(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    marksObtained = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.test} - {self.student}'
    
class StudentProgrammingTestScores(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    subjectCode = models.CharField(max_length=10, null=True, blank=True)
    specialization = models.CharField(max_length=50)
    marksObtained = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.test} - {self.student}'

class StudentCoreTestScores(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    marksObtained = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.test} - {self.student}'
    
class SubTests(models.Model):
    # A1, A2, L2, P4
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    subTestName = models.CharField(max_length=20)
    subTestDescription = models.CharField(max_length=200, default="Assignment Details published")
    subTestDeadline = models.DateField()
    maxMarks = models.FloatField(default=100)
    passingMarks = models.FloatField(default=50)

    def __str__(self):
        return f'{self.test.testName} \'{self.test.batch} : {self.subTestName}'
    
    class Meta:
        ordering = ['subTestDeadline', 'subTestName']

class StudentTest(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    subTest = models.ForeignKey(SubTests, on_delete=models.CASCADE)
    marksObtained = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.subTest.test.testName} : {self.subTest.subTestName} - {self.student.student.name}'
    
class Topic(models.Model):
    TOPICS = (
        ('General', 'General'),
        ('Drive', 'Drive'),
        ('Training - Aptitude', 'Training - Aptitude'),
        ('Training - Soft Skills', 'Training - Soft Skills'),
        ('Training - Java', 'Training - Java'),
        ('Training - Python', 'Training - Python'),
        ('Training - Core TYL', 'Training - Core TYL'),
    )

    name = models.CharField(max_length=200, choices=TOPICS)

    def __str__(self):
        return self.name

class ChatRoom(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-updated', '-created']

base/forms.py
from django.forms import ModelForm, Form, FileField
from .models import *
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'password1', 'password2']

class DriveForm(ModelForm):
    class Meta:
        model = Drives
        exclude = ['placement_officer', 'driveChat', 'created', 'updated']

class KYCForm(ModelForm):
    class Meta:
        model = KYC
        fields = '__all__'
        exclude = ['student', 'validation', 'comments']

class SPFForm(ModelForm):
    class Meta:
        model = SPF
        fields = '__all__'
        exclude = ['student', 'validation', 'comments']

class ChatRoomForm(ModelForm):
    class Meta:
        model = ChatRoom
        fields = '__all__'
        exclude = ['host', 'topic', 'participants', 'created', 'updated']

class TestForm(ModelForm):
    class Meta:
        model = Tests
        fields = '__all__'
        exclude = ['testType']

class SubTestForm(ModelForm):
    class Meta:
        model = SubTests
        fields = '__all__'
        exclude = ['test']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar']

class UploadMarksForm(Form):
    csv_file = FileField()

    def clean_file(self):
        uploaded_file = self.cleaned_data['csv_file']
        
        if not uploaded_file.name.endswith('.csv'):
            raise ValidationError("The uploaded file must be a .csv file")
        
        if uploaded_file.content_type != 'text/csv':
            raise ValidationError("The uploaded file must be a CSV (text/csv)")

        return uploaded_file

base/templates/base/chat_room.html
{% extends 'main.html' %}

{% block content %}

<main class="profile-page layout layout--2">
    <div class="container">
      <!-- Room Start -->
      <div class="room">
        <div class="room__top">
          <div class="room__topLeft">
            <a href="{% url 'home_page' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>CMRIT PLACEMENTS</h3>
          </div>
          
          {% if request.user == room.host %}
          <div class="room__topRight">
            <a href="#">
              <!-- <svg
                enable-background="new 0 0 24 24"
                height="32"
                viewBox="0 0 24 24"
                width="32"
                xmlns="http://www.w3.org/2000/svg"
              >
                <title>edit</title>
                <g>
                  <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                </g>
                <g>
                  <g>
                    <path
                      d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                    />
                  </g>
                  <g>
                    <path
                      d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                    />
                  </g>
                </g>
              </svg> -->
            </a>
            <a href="{% url 'delete_room' room.id %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
              </svg>
            </a>
          </div>
          {% endif %}
        </div>
        <div class="room__box scroll">
          <div class="room__header scroll">
            <div class="room__info">
              <h3>{{ room }}</h3>
              <span>{{ room.created | timesince }}</span>
            </div>
            <div class="room__hosted">
              <p>Hosted By</p>
              <a href="{% url 'user_profile' room.host.id %}" class="room__author">
                <div class="avatar avatar--small">
                  <img src="{{ room.host.avatar.url }}" />
                </div>
                <span>@{{ room.host.username }}</span>
              </a>
            </div>
            <div class="room__details">
              {{ room.description }}
            </div>
            <span class="room__topics">{{ room.topic }}</span>
          </div>
          <div class="room__conversation">
            <div class="threads scroll">
              {% for message in room_messages %}
              <div class="thread">
                <div class="thread__top">
                  <div class="thread__author">
                    <a href="{% url 'user_profile' message.sender.id %}" class="thread__authorInfo">
                      <div class="avatar avatar--small">
                        <img src="{{ message.sender.avatar.url }}" />
                      </div>
                      <span>@{{ message.sender.username }}</span>
                    </a>
                    <span class="thread__date">{{ message.created | timesince }}</span>
                  </div>
                  {% if request.user == message.sender %}
                  <a href="{% url 'delete_message' message.id %}">
                  <div class="thread__delete">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </div>
                  </a>
                  {% endif %}
                </div>
                <div class="thread__details">
                  {{ message.message }}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        {% if user.is_authenticated %}
        <div class="room__message">
          <form method="POST" action="">
            {% csrf_token %}
            <input name="message" placeholder="Write your message here..." />
          </form>
        </div>
        {% endif %}
      </div>
      <!-- Room End -->

      <!--   Start -->
      <div class="participants">
        <h3 class="participants__top">Participants <span>({{ room.participants.all.count }} Joined)</span></h3>
        <div class="participants__list scroll">
          {% for participant in participants %}
          <a href="" class="participant">
            <div class="avatar avatar--medium">
              <img src="{{ participant.avatar.url }}" />
            </div>
            <p>
              {{ participant.username }}
              <span>@{{ participant.username }}</span>
            </p>
          </a>
          {% endfor %}
        </div>
      </div>
      <!--  End -->
    </div>
  </main>

{% endblock %}

base/templates/base/create_chat_room.html
{% extends 'main.html' %}

{% block content %}
{% if page == 'drive' %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home_page' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Create New Drive</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="accordion">
            <div class="accordion__section">
              <div class="accordion__header">Batch & Company Details</div>
              <div class="accordion__content">
                <div class="form__group">
                  <label for="room_name">Batch</label>
                  {{ form.batch }}
                </div>
                <div class="form__group">
                  <label for="room_name">Company</label>
                  {{ form.companyName }}
                </div>
              </div>
            </div>
            <div class="accordion__section">
              <div class="accordion__header">Job Details</div>
                <div class="accordion__content">
                  <div class="form__group">
                    <label for="room_role">Role</label>
                    {{ form.role }}
                </div>
                <div class="form__group">
                    <label for="room_req">Requirements</label>
                    {{ form.requirements }}
                </div>
                <div class="form__group">
                    <label for="room_jd">Job Description</label>
                    {{ form.job_description }}
                </div>
                <div class="form__group">
                  <label for="room_jd">CGPA Requirements</label>
                  <input type="number" name="min_cgpa" id="" step="any">
              </div>
              </div>
            </div>
            <div class="accordion__section">
              <div class="accordion__header">TYL Criteria Details</div>
                <div class="accordion__content">
                  <div class="form__group">
                    <label for="room_ax">Ax Level</label>
                    {{ form.aptitude_level }}
                  </div>
                  <div class="form__group">
                      <label for="room_px">Px Level</label>
                      {{ form.programming_level }}
                  </div>
                  <div class="form__group">
                      <label for="room_px">Cx Level</label>
                      {{ form.core_level }}
                  </div>
                  <div class="form__group">
                    <label for="room_px">Lx Level</label>
                    <input type="number" name="language_level" id="">
                  </div>
                  <div class="form__group">
                    <label for="room_px">Sx Level</label>
                    <input type="number" name="softskills_level" id="">
                  </div>
                </div>  
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
              <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
  {% elif page == 'chat' %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home_page' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create New Chat</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}
            <div class="form__group">
              <label for="topic">Topic</label>
              <select name="topic">
              {% for topic in topics %}
                <option value="{{ topic }}">{{ topic }}</option>
              {% endfor %}
              </select>
            </div>
            {% for field in form %}
            <div class="form__group">
              <label for="{{ field.label }}">{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}
            <div class="form__action">
                <a class="btn btn--dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
                <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
  {% endif %}
{% endblock content %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'base/home_left.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    {% include 'base/home_center.html' %}
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/home_right.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

base/templates/base/spad_details.html
{% extends 'main.html' %}

{% block content %}

<main class="profile-page layout layout--2">
    <div class="container">
      <!-- Room Start -->
      <div class="roomList">
        <div></div>
        <div class="roomList__header">
            <div>
                <h2>SPAD Details</h2>
            </div>
            <!-- <p>
            <a class="btn btn--main" href="{% url 'spad_details' batch %}?op=extract">
              Extract to Excel
            </a>
            <a class="btn btn--main" href="{% url 'spad_details' batch %}?op=send_email">
                Send Email
            </a>
            </p> -->
        </div>
        <table>
            <thead>
            <tr>
                <th>USN</th>
                <th>Student</th>
                <th>Batch</th>
                <th>Branch</th>
                <th>Mobile Number (Calling)</th>
                <th>Communication Address</th>
                <th>Resume</th>
                <th>Aadhar Card</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
            <tr>
                <td>{{ student.usn }}</td>
                <td>{{ student.student.name }}</td>
                <td>{{ student.batch }}</td>
                <td>{{ student.branch }}</td>
                <td>
                    {% for spf in student.spf_set.all %}
                        {{ spf.mobileNumberForCalling }}
                    {% endfor %}
                </td>
                <td>
                    {% for spf in student.spf_set.all %}
                        {{ spf.communicationAddress }}
                    {% endfor %}
                </td>
                <td>
                    {% for kyc in student.kyc_set.all %}
                        {% if kyc.resume %}
                        <a href="{{ kyc.resume.url }}" target="_blank">{{ student.student.name }}'s Resume</a>
                        {% endif %}
                    {% endfor %}
                </td>
                <td>
                    {% for kyc in student.kyc_set.all %}
                        {% if kyc.aadharCard %}
                        <a href="{{ kyc.aadharCard.url }}" target="_blank">{{ student.student.name }}'s Aadhar Card</a>
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
            </tbody>    
        </table>
      </div>
      <!-- Room End -->

      <!--   Start -->
      <div class="topics">
        <div class="topics__header">
          <h2>Filter SPAD</h2>
        </div>
        <form class="form" action="" method="GET" style="display: inline-block">
            <p>
            <div class="form__group">
                <label for="usn_contains" style="text-transform: uppercase;">USN</label>
                {{ SPADFilter.form.usn }}
            </div>
            <div class="form__group">
                <label for="usn_contains" style="text-transform: uppercase;">Student Name</label>
                {{ SPADFilter.form.student_name }}
            </div>
            <div class="form__group">
                <label for="usn_contains" style="text-transform: uppercase;">Branch</label>
                {{ SPADFilter.form.branch }}
            </div>
            <div class="form__group">
                <label for="usn_contains" style="text-transform: uppercase;">Current Backlogs</label>
                {{ SPADFilter.form.currentBacklogs }}
            </div>
            <div class="form__group">
                <label for="usn_contains" style="text-transform: uppercase;">Degree CGPA</label>
                {{ SPADFilter.form.degreeCgpa }}
            </div>
            </p>
            <div class="form__action">
                <button class="btn btn--main" type="submit">Search</button>
            </div>
        </form>
      </div>
      <!--  End -->
    </div>
  </main>

{% endblock %}